-- Control Panel for Heaps n' Reaps

PLAYERS_PER_TEAM = 10

LOBBY_WAIT_TIME = 20
PRE_GAME_TIME = 10

SCAN_COOLDOWN = 60
SCAN_MAX_CHARGES = 5

STARTING_GOLD = 5000
GOLD_PER_TICK = 5
TICK_DURATION = 1

HERO_STARTING_LEVEL = 20

GAME_LENGTH = 600
KILL_STOPPAGE = 69

-- Modifiers
MAX_HEALTH_CAP = 999
BONUS_CAST_RANGE = 500
BONUS_VISION = 500
COOLDOWN_REDUCTION_PERCENTAGE = 50

KILL_SIZE_SCALING = 0.04
HOOK_KILL_RANGE_BONUS = 75          -- bonus hook (meat hook) range per kill


RESPAWN_TIME = 6